apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-docker-nginx-static-html-demo
  labels:
    app: kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes
  template:
    metadata:
      labels:
        app: kubernetes
    spec:
      containers:
      - name: kubernetes
        image: kubernetes-docker-nginx-static-html-demo:v1
        ports:
        - containerPort: 80