apiVersion: v1
kind: Service
metadata:
  name: kubernetes-docker-nginx-static-html-demo
spec:
  selector:
    app: kubernetes-docker-nginx-static-html-demo
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  clusterIP: 10.0.171.239
  loadBalancerIP: 78.11.24.19
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 146.148.47.155